using System;
using Dalamud.Game.ClientState.Keys;
using ImGuiNET;

namespace AllaganLib.Interface.Extensions;

public static class ImGuiKeyExtensions
{
    public static VirtualKey ToVirtualKey(this ImGuiKey imGuiKey)
    {
        if (imGuiKey == ImGuiKey.COUNT)
        {
            return VirtualKey.NO_KEY;
        }
        switch (imGuiKey)
        {
            case ImGuiKey.None:
                return VirtualKey.NO_KEY;
            case ImGuiKey.Tab:
                return VirtualKey.TAB;
            case ImGuiKey.LeftArrow:
                return VirtualKey.LEFT;
            case ImGuiKey.RightArrow:
                return VirtualKey.RIGHT;
            case ImGuiKey.UpArrow:
                return VirtualKey.UP;
            case ImGuiKey.DownArrow:
                return VirtualKey.DOWN;
            case ImGuiKey.PageUp:
                return VirtualKey.PRIOR;
            case ImGuiKey.PageDown:
                return VirtualKey.NEXT;
            case ImGuiKey.Home:
                return VirtualKey.HOME;
            case ImGuiKey.End:
                return VirtualKey.END;
            case ImGuiKey.Insert:
                return VirtualKey.INSERT;
            case ImGuiKey.Delete:
                return VirtualKey.DELETE;
            case ImGuiKey.Backspace:
                return VirtualKey.BACK;
            case ImGuiKey.Space:
                return VirtualKey.SPACE;
            case ImGuiKey.Enter:
                return VirtualKey.RETURN;
            case ImGuiKey.Escape:
                return VirtualKey.ESCAPE;
            case ImGuiKey.LeftCtrl:
                return VirtualKey.CONTROL;
            case ImGuiKey.LeftShift:
                return VirtualKey.SHIFT;
            case ImGuiKey.LeftAlt:
                return VirtualKey.MENU;
            case ImGuiKey.LeftSuper:
                return VirtualKey.LWIN;
            case ImGuiKey.RightCtrl:
                return VirtualKey.CONTROL;
            case ImGuiKey.RightShift:
                return VirtualKey.SHIFT;
            case ImGuiKey.RightAlt:
                return VirtualKey.MENU;
            case ImGuiKey.RightSuper:
                return VirtualKey.RWIN;
            case ImGuiKey.Menu:
                return VirtualKey.MENU;
            case ImGuiKey._0:
                return VirtualKey.KEY_0;
            case ImGuiKey._1:
                return VirtualKey.KEY_1;
            case ImGuiKey._2:
                return VirtualKey.KEY_2;
            case ImGuiKey._3:
                return VirtualKey.KEY_3;
            case ImGuiKey._4:
                return VirtualKey.KEY_4;
            case ImGuiKey._5:
                return VirtualKey.KEY_5;
            case ImGuiKey._6:
                return VirtualKey.KEY_6;
            case ImGuiKey._7:
                return VirtualKey.KEY_7;
            case ImGuiKey._8:
                return VirtualKey.KEY_8;
            case ImGuiKey._9:
                return VirtualKey.KEY_9;
            case ImGuiKey.A:
                return VirtualKey.A;
            case ImGuiKey.B:
                return VirtualKey.B;
            case ImGuiKey.C:
                return VirtualKey.C;
            case ImGuiKey.D:
                return VirtualKey.D;
            case ImGuiKey.E:
                return VirtualKey.E;
            case ImGuiKey.F:
                return VirtualKey.F;
            case ImGuiKey.G:
                return VirtualKey.G;
            case ImGuiKey.H:
                return VirtualKey.H;
            case ImGuiKey.I:
                return VirtualKey.I;
            case ImGuiKey.J:
                return VirtualKey.J;
            case ImGuiKey.K:
                return VirtualKey.K;
            case ImGuiKey.L:
                return VirtualKey.L;
            case ImGuiKey.M:
                return VirtualKey.M;
            case ImGuiKey.N:
                return VirtualKey.N;
            case ImGuiKey.O:
                return VirtualKey.O;
            case ImGuiKey.P:
                return VirtualKey.P;
            case ImGuiKey.Q:
                return VirtualKey.Q;
            case ImGuiKey.R:
                return VirtualKey.R;
            case ImGuiKey.S:
                return VirtualKey.S;
            case ImGuiKey.T:
                return VirtualKey.T;
            case ImGuiKey.U:
                return VirtualKey.U;
            case ImGuiKey.V:
                return VirtualKey.V;
            case ImGuiKey.W:
                return VirtualKey.W;
            case ImGuiKey.X:
                return VirtualKey.X;
            case ImGuiKey.Y:
                return VirtualKey.Y;
            case ImGuiKey.Z:
                return VirtualKey.Z;
            case ImGuiKey.F1:
                return VirtualKey.F1;
            case ImGuiKey.F2:
                return VirtualKey.F2;
            case ImGuiKey.F3:
                return VirtualKey.F3;
            case ImGuiKey.F4:
                return VirtualKey.F4;
            case ImGuiKey.F5:
                return VirtualKey.F5;
            case ImGuiKey.F6:
                return VirtualKey.F6;
            case ImGuiKey.F7:
                return VirtualKey.F7;
            case ImGuiKey.F8:
                return VirtualKey.F8;
            case ImGuiKey.F9:
                return VirtualKey.F9;
            case ImGuiKey.F10:
                return VirtualKey.F10;
            case ImGuiKey.F11:
                return VirtualKey.F11;
            case ImGuiKey.F12:
                return VirtualKey.F12;
            case ImGuiKey.Apostrophe:
                return VirtualKey.NO_KEY;
            case ImGuiKey.Comma:
                return VirtualKey.OEM_COMMA;
            case ImGuiKey.Minus:
                return VirtualKey.OEM_MINUS;
            case ImGuiKey.Period:
                return VirtualKey.OEM_PERIOD;
            case ImGuiKey.Slash:
                return VirtualKey.NO_KEY;
            case ImGuiKey.Semicolon:
                return VirtualKey.NO_KEY;
            case ImGuiKey.Equal:
                return VirtualKey.OEM_NEC_EQUAL;
            case ImGuiKey.LeftBracket:
                return VirtualKey.OEM_4;
            case ImGuiKey.Backslash:
                return VirtualKey.OEM_102;
            case ImGuiKey.RightBracket:
                return VirtualKey.OEM_6;
            case ImGuiKey.GraveAccent:
                return VirtualKey.NO_KEY;
            case ImGuiKey.CapsLock:
                return VirtualKey.CAPITAL;
            case ImGuiKey.ScrollLock:
                return VirtualKey.SCROLL;
            case ImGuiKey.NumLock:
                return VirtualKey.NUMLOCK;
            case ImGuiKey.PrintScreen:
                return VirtualKey.PRINT;
            case ImGuiKey.Pause:
                return VirtualKey.PAUSE;
            case ImGuiKey.Keypad0:
                return VirtualKey.NUMPAD0;
            case ImGuiKey.Keypad1:
                return VirtualKey.NUMPAD1;
            case ImGuiKey.Keypad2:
                return VirtualKey.NUMPAD2;
            case ImGuiKey.Keypad3:
                return VirtualKey.NUMPAD3;
            case ImGuiKey.Keypad4:
                return VirtualKey.NUMPAD4;
            case ImGuiKey.Keypad5:
                return VirtualKey.NUMPAD5;
            case ImGuiKey.Keypad6:
                return VirtualKey.NUMPAD6;
            case ImGuiKey.Keypad7:
                return VirtualKey.NUMPAD7;
            case ImGuiKey.Keypad8:
                return VirtualKey.NUMPAD8;
            case ImGuiKey.Keypad9:
                return VirtualKey.NUMPAD9;
            case ImGuiKey.KeypadDecimal:
                return VirtualKey.DECIMAL;
            case ImGuiKey.KeypadDivide:
                return VirtualKey.DIVIDE;
            case ImGuiKey.KeypadMultiply:
                return VirtualKey.MULTIPLY;
            case ImGuiKey.KeypadSubtract:
                return VirtualKey.SUBTRACT;
            case ImGuiKey.KeypadAdd:
                return VirtualKey.ADD;
            case ImGuiKey.KeypadEnter:
                return VirtualKey.RETURN;
            case ImGuiKey.KeypadEqual:
                return VirtualKey.OEM_NEC_EQUAL;
        }

        return VirtualKey.NO_KEY;
    }
}